name: TesseractUHC
main: com.martinbrook.tesseractuhc.TesseractUHC
version: 0.10.1
description: Useful commands for UHC matches
commands:
 tp:
  description: Teleportation functions
  usage: /tp | /tp player | /tp player destinationplayer | /tp x y z | /tp player x y z
 butcher:
  description: Butchers hostile mobs
  usage: /butcher
 tpd:
  description: Teleports to the last death point
  usage: /tpd
 tpl:
  description: Teleports to the last logout location
  usage: /tpl
 tpn:
  description: Teleports to the last notification
  usage: /tpn
 tps:
  description: Teleports to a player's start point
  usage: /tps start-number | playername
 tp0:
  description: Teleports to the overworld spawn point
  usage: /tp0
 tpp:
  description: Teleports to a POI
  usage: /tpp
 tpnext:
  description: Cycles through players
  usage: /tpnext
 tpback:
  description: Returns you to the position you were before your last teleport
  usage: /tpback
 setspawn:
  description: Sets the spawn point to your current location
  usage: /setspawn
 gm:
  description: Toggle gamemode between CREATIVE and SURVIVAL.
  usage: /gm
 heal:
  description: Heals a player
  usage: /heal player | *
 feed:
  description: Feeds a player
  usage: /feed player | *
 clearinv:
  description: Clears a player's inventory
  usage: /clearinv player | *
 renew:
  description: Feeds, heals and clearinvs a player
  usage: /renew player | *
 ready:
  description: Starts the match countdown
  usage: /ready seconds
 cdwb:
  description: Starts a world border countdown
  usage: /cdwb newradius seconds
 cdc:
  description: Cancels a running countdown
  usage: /cdc
 chatscript:
  description: Plays a chat script from a file, one line per second
  usage: /chatscript filename
 muteall:
  description: Mutes the chat so that nobody can talk except ops
  usage: /muteall on | off
 kill:
  description: Command disabled
  usage: /kill
 notify:
  description: Sends a private notification message to an admin
  usage: /notify Message
  aliases: n
 permaday:
  description: Enable/disable permaday
  usage: /permaday on | off
 uhc:
  description: UHC match configuration commands
  usage: /uhc commandtype parameters
 launch:
  description: Launch any players who haven't yet been launched
  usage: /launch
 relaunch:
  description: Relaunch a player
  usage: /relaunch player
 calcstarts:
  description: Calculate potential start points
  usage: /calcstarts type param1 param2
 tpcs:
  description: Teleport to a calculated start point
  usage: /tpcs number
 vi:
  description: View a player's inventory
  usage: /vi player
  aliases: pi
 setvanish:
  description: Update vanish status of all players on the server
  usage: /setvanish
 team:
  description: Create a new team
  usage: /team fullname
 join:
  description: Join a team
  usage: /join [team]
 leave:
  description: Leave the match
  usage: /leave
 matchinfo:
  aliases: [ mi, match ]
  description: Display status of the current match
  usage: /matchinfo
 params:
  description: Display match parameters
  usage: /params
 players:
  description: Commands for interacting with players
  usage: /players add | /players rm | /players
 teams:
  description: Commands for interacting with teams
  usage: /teams add | /teams rm | /teams
 interact:
  description: Enables/disables the ability for you to interact with the world
  usage: /interact
 spectate:
  description: Sets a dead player to specator
  usage: /spectate name
 pvp:
  description: Enables/disables PVP
  usage: /pvp on | off
 nv:
  description: Enables/disables night vision on spectators
  usage: /nv on | off
